---
trigger:
  batch: true
  branches:
    include:
      - master
pr:
  - master

stages:
  - stage: InvokeAPI
    jobs:
      - job: HTTPRequest
        pool: server
        steps:
          - task: InvokeRESTAPI@1
            displayName: "HTTPRequest"
            inputs:
              connectionType: 'connectedServiceName'
              serviceConnection: 'https://10.10.1.205'
              method: 'POST'
              headers: |
                {
                  "Authorization":"Basic QWNjZXNzS2V5OnNwZWN0cmFhZG1pbg==",
                  "Content-Type":"application/json"
                }
              body: '{"AssetType":"Unix based","AssetHost":"10.10.1.163","DBInstance":"","AccountName":"root","Instance":"Default"}'
              urlSuffix: '/API/APP/APP008/RequestPassword'
              waitForCompletion: 'false'
