---
- name: API CALL
  hosts: localhost
  tasks:
    - name: Call API Task
      uri:
        url: https://10.10.1.205:443/API/APP/APP008/SecretsOperations
        url_username: AccessKey
        url_password: spectraadmin
        method: POST
        body: {"SecretsGroupName":"Omkar01","SecretsSubgroupName":"Subtest01","Keys":"Scan_01","Value":"test","Action":"Select","Instance":"Default"}
        validate_certs: no
        return_content: yes
        force_basic_auth: yes
        status_code: 200
        body_format: json
      register: response
    - set_fact: result="{{ response.json.Result | replace('\r', '') | replace('\n', '') | replace('\', '') }}"
    - set_fact: stnpassword="{{ result.Value }}"
    - debug:
       var: stnpassword
    - set_fact: stnpassword='spectraadmin'
    - name: Call API with New Password
      uri:
        url: https://10.10.1.205:443/API/APP/APP008/SecretsOperations
        url_username: AccessKey
        url_password: "{{ stnpassword }}"
        method: POST
        body: {"SecretsGroupName":"Omkar01","SecretsSubgroupName":"Subtest01","Keys":"Scan_01","Value":"test","Action":"Select","Instance":"Default"}
        validate_certs: no
        return_content: yes
        force_basic_auth: yes
        status_code: 200
        body_format: json
      register: responsenew
    - debug:
       var: url_password
    - debug:
       var: stnpassword
    - debug:
       var: responsenew