#---
#- name: Ping Process All testservers
#  hosts: 10.10.1.163,10.10.1.164
#  remote_user: root
#  become: yes
#  tasks: 
#  - name: Ping Server
#    action: ping
#---
---
- name: Git Checkout 
  remote_user: root
  become: yes
  become_method: sudo
  hosts: 10.10.1.163,10.10.1.164
  gather_facts: no
  vars:
    git_user: VinodMandloi
    git_pass: Vella@2717
  tasks:
  - name: Ping Server
    action: ping
#  - name: Installing wget 
#    yum: pkg=wget state=present
