#---
#- name: Ping Process All testservers
# hosts: 10.10.1.163,10.10.1.164
#  remote_user: root
#  become: yes
#  tasks: 
#  - name: Ping Server
#    action: ping
---
- name: Git Checkout
  hosts: 10.10.1.163,10.10.1.164
  vars:
    repo_name: local-kvm-cloudimage
    git_user: VinodMandloi
    git_pass: Vella@2717
  tasks:
  - name: Ping Server
    git:
      repo: "https://{{git_user|urlencode()}}:{{git_pass|urlencode()}}@github.com/VinodMandloi/aspnetcorewebsite.git"
      dest: "/root/Ansible"
#  - name: Installing wget 
#    yum: pkg=wget state=present
